# Generated by Django 4.2.25 on 2025-11-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descargo_responsabilidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroingreso',
            name='ciudad_zona',
        ),
        migrations.RemoveField(
            model_name='registroingreso',
            name='nombre_zona',
        ),
        migrations.AddField(
            model_name='registroingreso',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_historial', to='descargo_responsabilidad.ubicacion', verbose_name='Zona Crítica'),
        ),
    ]
