# Generated by Django 4.2.25 on 2025-11-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descargo_responsabilidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroingreso',
            name='documento_asociado',
        ),
        migrations.RemoveField(
            model_name='registroingreso',
            name='ingresa_equipos',
        ),
        migrations.AddField(
            model_name='registroingreso',
            name='modalidad',
            field=models.CharField(choices=[('CON_EQUIPOS', 'Ingreso con Equipos'), ('SOLO_ACTIVIDADES', 'Solo Actividades'), ('VISITA', 'Solo Visita')], default='VISITA', max_length=20),
        ),
        migrations.AddField(
            model_name='registroingreso',
            name='pdf_descargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_origen_entrada', to='descargo_responsabilidad.documentopdf', verbose_name='PDF Descargo (Entrada)'),
        ),
        migrations.AddField(
            model_name='registroingreso',
            name='pdf_reporte_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_origen_salida', to='descargo_responsabilidad.documentopdf', verbose_name='PDF Reporte (Salida)'),
        ),
        migrations.AlterField(
            model_name='documentopdf',
            name='tipo',
            field=models.CharField(choices=[('DESCARGO', 'Descargo de Responsabilidad'), ('REPORTE_SALIDA', 'Reporte de Salida y Actividades'), ('DIAGNOSTICO', 'Diagnóstico Técnico'), ('OTRO', 'Otro Documento')], default='DESCARGO', max_length=20, verbose_name='Tipo de Documento'),
        ),
    ]
