# Generated by Django 4.2.25 on 2025-11-28 15:40

from django.db import migrations, models
import home.utils


class Migration(migrations.Migration):

    dependencies = [
        ('descargo_responsabilidad', '0002_remove_registroingreso_documento_asociado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopdf',
            name='archivo',
            field=models.FileField(max_length=255, upload_to=home.utils.GeneradorRutaArchivo('pdfs'), verbose_name='Archivo PDF'),
        ),
    ]
