# Generated by Django 4.2.25 on 2025-11-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descargo_responsabilidad', '0002_remove_registroingreso_ciudad_zona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroingreso',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente Registro Herramientas'), ('En Zona', 'En Zona'), ('Finalizado', 'Finalizado')], default='En Zona', max_length=20),
        ),
    ]
