# Generated by Django 4.2.25 on 2025-12-15 15:39

from django.db import migrations, models
import home.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título de la Actividad')),
                ('observacion_inicial', models.TextField(verbose_name='Observación Inicial')),
                ('foto_inicial', models.ImageField(upload_to=home.utils.GeneradorRutaArchivo('actividades/inicio'), verbose_name='Evidencia Inicial')),
                ('hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('observacion_final', models.TextField(blank=True, null=True, verbose_name='Observación Final')),
                ('foto_final', models.ImageField(blank=True, null=True, upload_to=home.utils.GeneradorRutaArchivo('actividades/fin'), verbose_name='Evidencia Final')),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='EN_PROCESO', max_length=20)),
            ],
            options={
                'verbose_name': 'Actividad Operativa',
                'verbose_name_plural': 'Bitácora de Actividades',
                'db_table': 'actividades_operativas',
            },
        ),
    ]
