# Generated by Django 4.2.25 on 2025-12-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('descargo_responsabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='registro_ingreso',
            field=models.ForeignKey(db_column='id_registro_ingreso', on_delete=django.db.models.deletion.CASCADE, related_name='actividades_registradas', to='descargo_responsabilidad.registroingreso', verbose_name='Ingreso Asociado'),
        ),
    ]
