# Generated by Django 4.2.25 on 2025-12-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='correo', max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario')], db_column='tipo', default='Usuario', max_length=250)),
                ('is_active', models.BooleanField(db_column='estado', default=True)),
                ('first_name', models.CharField(db_column='nombre', max_length=250)),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], db_column='tipo_documento', max_length=50)),
                ('numero_documento', models.CharField(db_column='numero_documento', max_length=50, unique=True)),
                ('token', models.CharField(blank=True, db_column='token', max_length=255, null=True)),
                ('img', models.ImageField(blank=True, db_column='img', max_length=250, null=True, upload_to='usuarios/')),
                ('tiempo_limite_jornada', models.TimeField(blank=True, db_column='tiempo_limite_jornada', null=True)),
                ('cargo', models.ForeignKey(blank=True, db_column='id_cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='empresas.cargo')),
                ('empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='empresas.empresa')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
    ]
