# Generated by Django 6.0 on 2025-12-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('codigo_ins', models.CharField(help_text='Ej: 211', max_length=20, verbose_name='Código INS')),
                ('nombre_aditivo', models.CharField(max_length=255, verbose_name='Nombre Aditivo')),
                ('categoria_alimento', models.CharField(help_text='Ej: 12.5 Sopas y caldos', max_length=255, verbose_name='Categoría Alimento')),
                ('limite_maximo_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Límite Máximo (ppm)')),
                ('fuente', models.CharField(default='CXS 192-1995', max_length=100, verbose_name='Fuente Normativa')),
            ],
            options={
                'verbose_name': 'Límite Normativo',
                'verbose_name_plural': 'Límites Normativos (Codex)',
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('codigo', models.CharField(help_text='Ej: MP51190028', max_length=50, unique=True, verbose_name='Código Interno (MP)')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('densidad', models.DecimalField(decimal_places=4, default=1.0, help_text='Fundamental para cálculos de volumen a masa.', max_digits=8, verbose_name='Densidad (g/ml)')),
                ('costo_kilo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo por Kg')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materias Primas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='InformacionNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sodio_mg', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Sodio (mg)')),
                ('azucares_g', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Azúcares Totales (g)')),
                ('azucares_anadidos_g', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Az. Añadidos (g)')),
                ('grasa_total_g', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Grasa Total (g)')),
                ('grasa_saturada_g', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Grasa Saturada (g)')),
                ('proteina_g', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Proteína (g)')),
                ('carbohidratos_g', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Carbohidratos (g)')),
                ('materia_prima', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutricional', to='catalogo.materiaprima')),
            ],
            options={
                'verbose_name': 'Info. Nutricional',
                'verbose_name_plural': 'Info. Nutricional',
            },
        ),
    ]
