# Generated by Django 6.0 on 2025-12-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionTecnologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Función')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción (Opcional)')),
            ],
            options={
                'verbose_name': 'Función Tecnológica',
                'verbose_name_plural': 'Funciones Tecnológicas',
                'ordering': ['nombre'],
            },
        ),
    ]
