# Generated by Django 4.2.25 on 2025-11-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table='empresas',
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='empresa_servicios',
        ),
    ]
