"""
Django settings for zonascriticas project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Usamos parent para subir los directorios
env_path = BASE_DIR.parent / '.env'
load_dotenv(dotenv_path=env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# ➡️ 
SECRET_KEY = os.getenv('SECRET_KEY', 'Fallo')

# ➡️ Esta configuración sirve para realizar un DEBUG: Nos va a saltar un error de Django diciendo que tenemos mal
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# ➡️ Esta configuracion nos evita tener ataques de dominio con HOST HEADER
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# Application definition: Eliminamos las tres lineas porque no las vamos a usar para nuestra base de datos
# Vamos a personalizar nuestro propio sistema de login

# ➡️ Le decimos a Django cuales son las apps que vamos a usar
INSTALLED_APPS = [
    #'django.contrib.admin',
    #'django.contrib.auth',
    #'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'home',
    'perfil',
    'empresas',
    'descargo_responsabilidad',
    'registro_herramientas',
]

#➡️ Este es nuestro scanner de seguridad: este es el filtro que deben pasar las peticiones y las respuestas
# Estos middleware se ejecutan en orden
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    #'django.contrib.auth.middleware.AuthenticationMiddleware', 
    'login.middleware.CustomAuthMiddleware', # Nuestro middleware para autenticacion personalizado
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ➡️ Esta configuracion es para nuestro enrutamiento de urls.py con la de  ZONASCRITICAS
ROOT_URLCONF = 'zonascriticas.urls'

# ➡️ Esta configuracion nos sirve para poder utilizar de manera adecuada el DTL: Django Templates 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # DIR BUSCA LA DIRECCION DE LA CARPETA TEMPALTES
        'APP_DIRS': True, # LE DICE A DJANGO BUSCA: login/templates/login.html SI LO ENCUENTRA LO RENDERIZA
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zonascriticas.wsgi.application'


#AUTH_USER_MODEL = 'login.Usuario'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),       
        'PASSWORD': os.getenv('DB_PASSWORD', ''), 
        'HOST': os.getenv('DB_HOST', ''),       
        'PORT': os.getenv('DB_PORT', ''),     
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# -------- si le cambias el bombre a media aqui solo cambiar ''
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CONFIGURACIÓN DE CORREO (SMTP) ---
# Esto conecta Django con las variables de tu .env (Mailtrap)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Conversión explícita: El .env devuelve texto, Django necesita Booleano
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# Configuraciones de seguridad 🚨🚨🚨🚨

# 1. Evita que JavaScript acceda a la cookie de sesión (Anti-XSS)
SESSION_COOKIE_HTTPONLY = True

# 2. La cookie solo se envía en conexiones HTTPS (Activar en Producción, Falso en Dev local si no tienes SSL)
# Como usas .env, lo ligamos a tu variable DEBUG. Si NO es debug, es True.
SESSION_COOKIE_SECURE = False if DEBUG else True 
CSRF_COOKIE_SECURE = False if DEBUG else True

# 3. Protección contra Cross-Site Request Forgery
SESSION_COOKIE_SAMESITE = 'Lax' 

# 4. Cierra la sesión si el usuario cierra el navegador (Opcional, pero recomendado para empresas)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 5. Motor de Sesión (Usaremos base de datos por defecto, es seguro)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# CONFIGURACION PARA MANEJAR EL BLOQUEO DE IPs
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'seguridad_cache', # AQUI COLOCAMOS EL NOMBRE DE LA TABLA
    }
}

# OBSERVACIÓN: Cuando se monte este proyecto en producción se debe ejecutar de nuevo el comando
# python manage.py createchachetable