# Generated by Django 4.2.25 on 2025-12-15 15:39

from django.db import migrations, models
import django.db.models.deletion
import home.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('descargo_responsabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('HERRAMIENTA', 'Herramienta / Equipo General'), ('COMPUTO', 'Activo de Cómputo / Tecnológico')], db_index=True, default='HERRAMIENTA', max_length=20, verbose_name='Tipo de Activo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Activo')),
                ('marca_serial', models.CharField(max_length=255, verbose_name='Marca / Serial')),
                ('foto_referencia', models.ImageField(blank=True, db_column='foto_referencia_ruta', null=True, upload_to=home.utils.GeneradorRutaArchivo('herramientas/inventario'), verbose_name='Foto de Referencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='mi_inventario', to='login.usuario', verbose_name='Dueño')),
            ],
            options={
                'verbose_name': 'Ítem de Inventario',
                'verbose_name_plural': 'Inventario Personal',
                'db_table': 'inventario_herramientas',
            },
        ),
        migrations.CreateModel(
            name='HerramientaIngresada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('foto_evidencia', models.ImageField(blank=True, db_column='foto_ingreso_ruta', null=True, upload_to=home.utils.GeneradorRutaArchivo('herramientas/evidencias'), verbose_name='Foto Evidencia del Día')),
                ('estado', models.CharField(choices=[('INGRESADO', 'En Planta'), ('SALIO', 'Retirado')], default='INGRESADO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('herramienta_inventario', models.ForeignKey(db_column='id_inventario_activo', on_delete=django.db.models.deletion.PROTECT, related_name='historial_ingresos', to='registro_herramientas.inventarioherramienta')),
                ('registro_ingreso', models.ForeignKey(db_column='id_registro_ingreso', on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_registradas', to='descargo_responsabilidad.registroingreso')),
            ],
            options={
                'verbose_name': 'Registro de Herramienta',
                'verbose_name_plural': 'Herramientas Ingresadas',
                'db_table': 'registros_herramientas_ingreso',
            },
        ),
    ]
