# Generated by Django 4.2.25 on 2025-11-25 13:47

from django.db import migrations, models
import registro_herramientas.utils


class Migration(migrations.Migration):

    dependencies = [
        ('registro_herramientas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientaingresada',
            name='foto_evidencia',
            field=models.ImageField(blank=True, db_column='foto_ingreso_ruta', null=True, upload_to=registro_herramientas.utils.path_evidencia_ingreso, verbose_name='Foto Evidencia del Día'),
        ),
    ]
