# Generated by Django 6.0 on 2025-12-26 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_funciontecnologica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Ficha (PP)')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('version_actual', models.PositiveIntegerField(default=1, verbose_name='Versión Matemática')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (Edición)'), ('VIGENTE', 'Vigente (Aprobado)'), ('OBSOLETO', 'Obsoleto (Histórico)')], default='BORRADOR', max_length=10)),
                ('cantidad_base_lote', models.DecimalField(decimal_places=2, default=1000.0, help_text='Variable VERDE: Base para calcular Kgs reales.', max_digits=10, verbose_name='Base Lote (Kg)')),
                ('densidad_teorica', models.DecimalField(decimal_places=4, default=1.0, help_text='Variable MORADA: Si este producto se usa como ingrediente, se usa esta densidad.', max_digits=8, verbose_name='Densidad Teórica (g/ml)')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto (Ficha Técnica)',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ItemFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('cantidad_porcentaje', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='% Cantidad')),
                ('porcentaje_uso', models.DecimalField(decimal_places=4, default=100.0, help_text='Variable MORADA: Dosis usada por el cliente final.', max_digits=8, verbose_name='% Uso (Cliente)')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.funciontecnologica', verbose_name='Función Tecnológica')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.materiaprima', verbose_name='Ingrediente (MP)')),
                ('norma_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.limitenormativo', verbose_name='Norma Codex')),
                ('producto_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='formulador.producto')),
                ('sub_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usado_como_ingrediente', to='formulador.producto', verbose_name='Ingrediente (Sub-Producto)')),
            ],
            options={
                'verbose_name': 'Renglón de Fórmula',
                'verbose_name_plural': 'Renglones de Fórmula',
            },
        ),
        migrations.CreateModel(
            name='HistorialFichas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='fichas_tecnicas/%Y/%m/', verbose_name='Documento PDF')),
                ('version', models.PositiveIntegerField(verbose_name='Versión Documental')),
                ('comentario', models.TextField(blank=True, verbose_name='Razón del cambio / Comentarios')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pdfs', to='formulador.producto')),
            ],
            options={
                'verbose_name': 'Archivo de Ficha Técnica',
                'verbose_name_plural': 'Historial de Fichas',
                'ordering': ['-version'],
            },
        ),
    ]
